package com.forum.entity;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="forum_db"
)
public class Category  implements java.io.Serializable {


     private Integer idCategory;
     private String name;
     private String description;
     private String status;
     private Set<FilDiscussion> filDiscussions = new HashSet<FilDiscussion>(0);

    public Category() {
    }

	
    public Category(String name, String status) {
        this.name = name;
        this.status = status;
    }
    public Category(String name, String description, String status, Set<FilDiscussion> filDiscussions) {
       this.name = name;
       this.description = description;
       this.status = status;
       this.filDiscussions = filDiscussions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_category", unique=true, nullable=false)
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<FilDiscussion> getFilDiscussions() {
        return this.filDiscussions;
    }
    
    public void setFilDiscussions(Set<FilDiscussion> filDiscussions) {
        this.filDiscussions = filDiscussions;
    }

    @Override
    public String toString() {
       
        return this.name ;
        //+" "+this.description+" "+this.status
    }




}


