package com.forum.entities;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="comment"
    ,catalog="forum_db"
)
public class Comment  implements java.io.Serializable {


     private Integer idComment;
     private User user;
     private FilDiscussion filDiscussion;
     private String contents;
     private Date dateComment;
     private String status;

    public Comment() {
    }

    public Comment(User user, FilDiscussion filDiscussion, String contents, Date dateComment, String status) {
       this.user = user;
       this.filDiscussion = filDiscussion;
       this.contents = contents;
       this.dateComment = dateComment;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_comment", unique=true, nullable=false)
    public Integer getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(Integer idComment) {
        this.idComment = idComment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fil_discussion", nullable=false)
    public FilDiscussion getFilDiscussion() {
        return this.filDiscussion;
    }
    
    public void setFilDiscussion(FilDiscussion filDiscussion) {
        this.filDiscussion = filDiscussion;
    }

    
    @Column(name="contents", nullable=false, length=65535)
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_comment", nullable=false, length=0)
    public Date getDateComment() {
        return this.dateComment;
    }
    
    public void setDateComment(Date dateComment) {
        this.dateComment = dateComment;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "{[id:"+this.idComment+"],[contents:"+this.contents+"],[Date:"+this.dateComment+"],[status:"+this.status+"]}"; //To change body of generated methods, choose Tools | Templates.
    }




}


