package com.forum.entities;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FilDiscussion generated by hbm2java
 */
@Entity
@Table(name="fil_discussion"
    ,catalog="forum_db"
)
public class FilDiscussion  implements java.io.Serializable {


     private Integer idFilDiscussion;
     private User user;
     private Category category;
     private String subject;
     private String contents;
     private String type;
     private Date dateDiscussion;
     private  String status;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public FilDiscussion() {
    }

	
    public FilDiscussion(User user, Category category, String subject, String contents, String type, Date dateDiscussion,  String status) {
        this.user = user;
        this.category = category;
        this.subject = subject;
        this.contents = contents;
        this.type = type;
        this.dateDiscussion = dateDiscussion;
        this.status = status;
    }
    public FilDiscussion(User user, Category category, String subject, String contents, String type, Date dateDiscussion,  String status, Set<Comment> comments) {
       this.user = user;
       this.category = category;
       this.subject = subject;
       this.contents = contents;
       this.type = type;
       this.dateDiscussion = dateDiscussion;
       this.status = status;
       this.comments = comments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_fil_discussion", unique=true, nullable=false)
    public Integer getIdFilDiscussion() {
        return this.idFilDiscussion;
    }
    
    public void setIdFilDiscussion(Integer idFilDiscussion) {
        this.idFilDiscussion = idFilDiscussion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_category", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="subject", nullable=false)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="contents", nullable=false, length=65535)
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

     @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_discussion", nullable=false)
    public Date getDateDiscussion() {
        return this.dateDiscussion;
    }
    
    public void setDateDiscussion(Date dateDiscussion) {
        this.dateDiscussion = dateDiscussion;
    }

   @Column(name="status", nullable=false, length=50) 
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus( String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filDiscussion")
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }


public String toString(){
    return "[id:"+this.idFilDiscussion+",subject:"+this.subject +",type:"+this.type+"]";
}

}


