package com.forum.entities;
// Generated 25 fevr. 2015 16:41:06 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="forum_db"
)
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Role role;
     private String login;
     private String password;
     private String email;
     private String firstName;
     private String lastName;
     private Date birthdate;
     private String status;
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<FilDiscussion> filDiscussions = new HashSet<FilDiscussion>(0);
     private Set<PhotoUserProfile> photoUserProfiles = new HashSet<PhotoUserProfile>(0);

    public User() {
    }

	
    public User(Role role, String login, String password, String email, String firstName, String lastName, Date birthdate, String status) {
        this.role = role;
        this.login = login;
        this.password = password;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthdate = birthdate;
        this.status = status;
    }
    public User(Role role, String login, String password, String email, String firstName, String lastName, Date birthdate, String status, Set<Comment> comments, Set<FilDiscussion> filDiscussions, Set<PhotoUserProfile> photoUserProfiles) {
       this.role = role;
       this.login = login;
       this.password = password;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthdate = birthdate;
       this.status = status;
       this.comments = comments;
       this.filDiscussions = filDiscussions;
       this.photoUserProfiles = photoUserProfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_user", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_role", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="login", nullable=false, length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", nullable=false, length=0)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<FilDiscussion> getFilDiscussions() {
        return this.filDiscussions;
    }
    
    public void setFilDiscussions(Set<FilDiscussion> filDiscussions) {
        this.filDiscussions = filDiscussions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<PhotoUserProfile> getPhotoUserProfiles() {
        return this.photoUserProfiles;
    }
    
    public void setPhotoUserProfiles(Set<PhotoUserProfile> photoUserProfiles) {
        this.photoUserProfiles = photoUserProfiles;
    }

    @Override
    public String toString() {
        return "[firstname:"+this.firstName+ ",lastName:" +this.lastName
                +",email:"+this.email+",login:"+this.login+",password:"+this.password+"]";
    }




}


